### ISSUE TITLE
How to program BA004: Wifi Single Dimmer (triac based) non Atmega328p version

### ISSUE THREAD

**Issue by thomas-lentz** [armtronix/Wifi-Single-Dimmer-Board#1]
Hi,
I bought your Armtronix Esp8266 based Single Triac Dimmer Board with free casing without Atmega328p.
I'd like to reprogram that, but I can't find any Arduino or Tasmota Code for your standalone ESP version. Since there is also no schematic available I would have to reengineer my dimmer, to integrate the Atmega328p source code into the ESP code.
Frankly said, I would rather not do that. Could you point me where to find the correct source code?

Kind regards
 Thomas

**Comment by armtronix** [comment]
https://github.com/armtronix/Wifi-Single-Dimmer-Board/tree/master/Wifi-Single-Dimmer-Board/Arduino_Code/Wifi_Single_dimmer_only_espV0.2
you can use the above link code . there is no tasmota as hw_timer.c is resource consuming  . I suggest first power on the device it will have this basic code loaded by default . Later on you can modify it

**Comment by thomas-lentz** [comment]
Okay, I will try that. Thank you.
